config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :trackers do
    post :track_movement, on: :member
    post :stop_track_movement, on: :member
  end

  post 'sms_callback' => 'callbacks#sms', as: :sms_callback

end

app/models/api_request.rb
class ApiRequest < ActiveRecord::Base
end

app/models/movement.rb
class Movement < ActiveRecord::Base
  scope :within_time_window, ->(opts) {
    reported_at = Movement.arel_table[:reported_at]

    where(
      reported_at.gt(opts[:time_window_start]).and(
        reported_at.lt(opts[:time_window_end]))
      )
  }
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  bitmask :modes, as: %i{track_movement}, null: false

  has_many :movements

  def tracking_movement?
    modes? :track_movement
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trackers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def sms
    from = params.fetch('From', '')
    text = params.fetch('Body', '')

    if tracker = Tracker.where(phone_number: from).first
      case text
      when /^move ok!/
        tracker.modes << :track_movement
        tracker.save!
      when /^move!/
        lat         = text[/lat:([^ ]+)/, 1]
        lng         = text[/long:([^ ]+)/, 1]
        speed       = text[/speed:([^ ]+)/, 1]
        reported_at = text[/T:([^ ]+ [^ ]+)/, 1]

        tracker.movements.create!(
          lat: lat, lng: lng, speed: speed, reported_at: Time.strptime(reported_at, "%D %H:%M")
        )
      when /^nomove ok!/
        tracker.modes.delete :track_movement
        tracker.save!
      end
    end

    head :ok
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_tracker, only: [:edit, :update, :destroy, :track_movement,
                                     :stop_track_movement]

  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = current_user.trackers
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
    @tracker = Tracker.find(params[:id])

    # convert param values from epoch to datetime
    slider_params = Hash[(params[:q] || {}).map {|k,v| [k, Time.at(v.to_f)]}]

    @slider_params = ActiveSupport::HashWithIndifferentAccess[
      time_window_start: 3.days.ago,
      time_window_end: Time.now,
      time_window_min: 1.week.ago,
      time_window_max: Time.now
    ].merge(slider_params)

    @movements = @tracker.movements.within_time_window(
      @slider_params.slice(:time_window_start, :time_window_end))
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = current_user.trackers.build(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to @tracker, notice: 'Tracker was successfully created.' }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: 'Tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def track_movement
    tracker_api.track_movement(true)

    redirect_to @tracker, notice: 'Request sent to tracker.'
  end

  def stop_track_movement
    tracker_api.track_movement(false)

    redirect_to @tracker, notice: 'Request sent to tracker.'
  end

  private
    def tracker_api
      @tracker_api ||= TrackerAPI.new(@tracker)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = current_user.trackers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit!
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user.present?
      redirect_to trackers_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "trackery" %></title>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <% if notice.present? %>
      <div class="alert-box-container">
        <div data-alert class="alert-box info radius">
          <%= notice %>
          <a href="#" class="close">&times;</a>
        </div>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert-box-container">
        <div data-alert class="alert-box alert radius">
          <%= alert %>
          <a href="#" class="close">&times;</a>
        </div>
      </div>
    <% end %>

    <div id="loading_overlay"></div>

    <%= yield %>

    <%= yield :javascript %>

  </body>
</html>

app/views/trackers/_form.html.erb
<%= simple_form_for(@tracker) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :phone_number %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trackers/_map.js.erb
function initMap() {
  var coordinates = []

  <% unless Rails.env.production? %>
    window.testCoordinates = []
  <% end %>

  <% movements.each do |m| %>
    <% unless Rails.env.production? %>
      window.testCoordinates.push([<%= m.lat %>, <%= m.lng %>])
    <% end %>

    coordinates.push( new google.maps.LatLng(<%= m.lat %>, <%= m.lng %>) )
  <% end %>

  if (coordinates.length == 0)
    return

  var mapOptions      = { zoomControl: true },
      bounds          = new google.maps.LatLngBounds(),
      infoStartWindow = new google.maps.InfoWindow({ content: "First reported position" }),
      infoEndWindow   = new google.maps.InfoWindow({ content: "Last reported position" }),
      map          = new google.maps.Map(document.getElementById('<%= map_container_id %>'), mapOptions)

  var listener = google.maps.event.addListener(map, "idle", function () {
      map.setOptions({maxZoom: 20});
      google.maps.event.removeListener(listener);
  });

  coordinates.forEach(function(p) {
    bounds.extend(p)
  })

  var polyline = new google.maps.Polyline({
    path: coordinates,
    geodesic: true,
    strokeColor: '#FF0000',
    strokeOpacity: 1.0,
    strokeWeight: 2
  });

  var startMarker = new google.maps.Marker({
      position: coordinates[0],
      map: map,
      title: "First reported position",
      icon: "http://maps.google.com/mapfiles/ms/icons/yellow-dot.png"
  })

  var endMarker = new google.maps.Marker({
      position: coordinates[coordinates.length - 1],
      map: map,
      title: "Last reported position",
      icon: "http://maps.google.com/mapfiles/ms/icons/green-dot.png"
  })

  google.maps.event.addListener(startMarker, 'click', function() {
      infoStartWindow.open(map, startMarker)
  })

  google.maps.event.addListener(endMarker, 'click', function() {
      infoEndWindow.open(map, endMarker)
  })

  map.fitBounds(bounds)
  polyline.setMap(map);

  $(document).off("ready page:load", initMap)
}

$(document).on("ready page:load", initMap)

app/views/trackers/_slider.js.erb
function initSlider() {
  var $slider = $('#slider'),
      $sliderForm = $slider.parent('form'),
      time_window_min = <%= slider_params[:time_window_min].to_i %>,
      time_window_max = <%= slider_params[:time_window_max].to_i %>,
      time_window_start = <%= slider_params[:time_window_start].to_i %>,
      time_window_end = <%= slider_params[:time_window_end].to_i %>,
      currentScale = moment.duration(time_window_max - time_window_min, 'seconds')

  $slider.noUiSlider({
      connect: true,
      start: [time_window_start, time_window_end],
      range: {
        min: time_window_min,
        max: time_window_max
      }
  }, true)

  var showDate = {
    to: function(value) {
      return (new Date(value * 1000)).toDateString()
    }
  }

  $slider.noUiSlider_pips({
      mode: 'count',
      values: currentScale.asDays() < 7 ? 2 : 7,
      density: 3,
      format: showDate
  })

  $slider.Link('lower').to("q[time_window_start]")
  $slider.Link('upper').to("q[time_window_end]")

  var isDragging

  $slider.on({
    slide: function() {
      setTimeout(function() {
          isDragging = true
      }, 300)
    },
    change: function() {
      setTimeout(function() {
          $sliderForm.submit()
        }, isDragging ? 0 : 300)
    }
  })

  if (currentScale.asDays() <= 1) {
    $('.scale-button-right').addClass('scale-button-disabled')
  }

  $slider.find('.scale-button:not(.scale-button-disabled)').click(function() {
      var $minInput = $sliderForm.find('input[name="q[time_window_min]"]'),
          $maxInput = $sliderForm.find('input[name="q[time_window_max]"]'),
          newMin, newMax

      if ($(this).hasClass('scale-button-left')) {
        var currentSliderDuration = time_window_max - time_window_min

        newMin = time_window_min - currentSliderDuration/2
        newMax = time_window_max + currentSliderDuration/2

        var futureDelta = newMax - Math.floor((new Date()).getTime() / 1000)

        if (futureDelta > 0) {
          newMin -= futureDelta
          newMax -= futureDelta
        }
      }
      else {
        newMin = time_window_start
        newMax = time_window_end
      }

      $minInput.val(newMin)
      $maxInput.val(newMax)

      $sliderForm.submit()
  })

  $(document).off('page:load', initSlider)
}

$(document).on('ready page:load', initSlider)

app/views/trackers/edit.html.erb
<h1>Editing Tracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/index.html.erb
<h1>Listing Trackers</h1>

<table>
  <thead>
    <tr>
      <th>Phone Number</th>
      <th>State</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= link_to tracker.phone_number, tracker %></td>
        <td>
          <% state = if tracker.tracking_movement? then 'on' else 'off' end %>
          <i class="icon-globe-alt <%= "state-%s" % state %>" title="track movement is <%= state %>"></i>
        </td>
        <td><%= link_to 'Edit', edit_tracker_path(tracker) %></td>
        <td><%= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracker', new_tracker_path %>

app/views/trackers/new.html.erb
<h1>New Tracker</h1>

<%= render 'form' %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/show.html.erb
<% if @movements.present? %>
  <div id="map-canvas"></div>
<% else %>
  <div class="alert-box-container">
    <div data-alert class="alert-box info radius">
      No tracks for this time window
      <a href="#" class="close">&times;</a>
    </div>
  </div>
<% end %>

<%= form_tag @tracker, turboboost: true, method: :get do %>
  <%= hidden_field_tag 'q[time_window_min]', @slider_params[:time_window_min].to_i %>
  <%= hidden_field_tag 'q[time_window_max]', @slider_params[:time_window_max].to_i %>

  <div id="slider">
    <div class="scale-button scale-button-left">
      <i class="icon-minus-circle"></i>
    </div>
    <div class="scale-button scale-button-right">
      <i class="icon-plus-circle"></i>
    </div>
  </div>
<% end %>

<% if current_user && current_user.trackers.include?(@tracker) %>
  <% if @tracker.tracking_movement? %>
    <%= button_to "Stop Track Movement", { action: 'stop_track_movement', id: @tracker }, { class: 'button' } %>
  <% else %>
    <%= button_to "Track Movement", { action: 'track_movement', id: @tracker }, { class: 'button' } %>
  <% end %>

  <%= link_to 'Edit', edit_tracker_path(@tracker) %> |
  <%= link_to 'Back', trackers_path %>
<% end %>

<% content_for :javascript do %>
  <script type="text/javascript" charset="utf-8">
    <%= render 'map.js', movements: @movements, map_container_id: 'map-canvas' %>
    <%= render 'slider.js', tracker: @tracker, slider_params: @slider_params %>
  </script>
<% end %>